name: 'Generate Datadog Entity'
description: 'Generate entity.datadog.yaml file based on CI workflow information'
author: 'Mottu-ops'

branding:
  icon: 'file-text'
  color: 'purple'

inputs:
  force:
    description: 'Force overwrite existing entity.datadog.yaml file'
    required: false
    default: 'false'
  
  working-directory:
    description: 'Working directory where to generate the file'
    required: false
    default: '.'
  
  commit-and-push:
    description: 'Automatically commit and push the generated file'
    required: false
    default: 'false'
  
  commit-message:
    description: 'Custom commit message for the generated file'
    required: false
    default: 'chore: generate/update entity.datadog.yaml'
  
  github-token:
    description: 'GitHub token for pushing changes (use secrets.GITHUB_TOKEN or secrets.PAT)'
    required: false
    default: ''

outputs:
  file-generated:
    description: 'Whether the file was generated (true/false)'
  
  file-path:
    description: 'Path to the generated file'
  
  project-type:
    description: 'Detected project type (angular/nestjs/dotnet/python)'

runs:
  using: 'composite'
  steps:
    - name: Generate Datadog Entity
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Set force flag if requested
        FORCE_FLAG=""
        if [[ "${{ inputs.force }}" == "true" ]]; then
          FORCE_FLAG="--force"
        fi
        
        # Run the generator script
        bash ${{ github.action_path }}/generate-datadog-entity.sh $FORCE_FLAG
        
        # Set outputs
        if [[ -f "entity.datadog.yaml" ]]; then
          echo "file-generated=true" >> $GITHUB_OUTPUT
          echo "file-path=$(pwd)/entity.datadog.yaml" >> $GITHUB_OUTPUT
        else
          echo "file-generated=false" >> $GITHUB_OUTPUT
          echo "file-path=" >> $GITHUB_OUTPUT
        fi
        
        # Try to detect project type from generated file or workflow
        PROJECT_TYPE="unknown"
        if [[ -f "entity.datadog.yaml" ]]; then
          if grep -q "project-type:angular" entity.datadog.yaml; then
            PROJECT_TYPE="angular"
          elif grep -q "project-type:nestjs" entity.datadog.yaml; then
            PROJECT_TYPE="nestjs"
          elif grep -q "project-type:dotnet" entity.datadog.yaml; then
            PROJECT_TYPE="dotnet"
          elif grep -q "project-type:python" entity.datadog.yaml; then
            PROJECT_TYPE="python"
          fi
        fi
        echo "project-type=$PROJECT_TYPE" >> $GITHUB_OUTPUT
    
    - name: Commit and Push Changes
      if: inputs.commit-and-push == 'true' && hashFiles('entity.datadog.yaml') != ''
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Configure git with Mottu credentials
        git config --global user.email "tech@mottu.com.br"
        git config --global user.name "tech-mottu"
        
        # Set up authentication if token is provided
        if [[ -n "${{ inputs.github-token }}" ]]; then
          git remote set-url origin https://x-access-token:${{ inputs.github-token }}@github.com/${{ github.repository }}.git
        fi
        
        # Check if there are changes to commit
        if git diff --quiet entity.datadog.yaml 2>/dev/null; then
          echo "No changes to commit in entity.datadog.yaml"
          exit 0
        fi
        
        # Add and commit the file
        git add entity.datadog.yaml
        git commit -m "${{ inputs.commit-message }}"
        
        # Push changes
        git push origin HEAD:${{ github.ref_name }}
        
        echo "✅ Successfully committed and pushed entity.datadog.yaml"
